# Generated by Django 5.0.4 on 2024-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subtext',
            field=models.CharField(default='', max_length=500),
        ),
    ]
