# Generated by Django 5.0.4 on 2024-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_question_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
